# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0009_auto_20151127_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Descriptive text for the LTI consumer.', max_length=200)),
                ('key', models.CharField(help_text=b'The key to be used by the LTI consumer.', max_length=20)),
                ('secret', models.CharField(help_text=b'The secret to be used by the LTI consumer.', max_length=20)),
            ],
        ),
    ]
