# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 20:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0013_assignment_test_compile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment_test_support',
            field=models.FileField(blank=True, help_text=b'An archive of files that should always be in the directory, beside the student files, during compilation / validation / full test.', null=True, upload_to=b'testscripts', verbose_name=b'Support files'),
        ),
    ]
