# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 09:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0015_auto_20161103_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='hard_deadline',
            field=models.DateTimeField(blank=True, help_text=b'Deadline after which submissions are no longer possible.', null=True),
        ),
    ]
