# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 10:37


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0016_auto_20171010_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gradingScheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='opensubmit.GradingScheme', verbose_name=b'grading scheme'),
        ),
    ]
