# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 21:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0017_auto_20171010_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to=b'assignment_desc', verbose_name=b'Assignment description'),
        ),
    ]
