# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 21:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0018_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='download',
            field=models.URLField(blank=True, null=True, verbose_name=b'Link for assignment description'),
        ),
    ]
