# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0025_remove_assignment_attachment_test_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment_test_compile',
        ),
    ]
