# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0027_auto_20171127_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='upload_filename',
            field=models.CharField(default='student.upload', max_length=255),
        ),
    ]
