# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0029_auto_20171127_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmachine',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Test machines can be temporarily disabled for maintenance. All jobs are held back during that time.'),
        ),
    ]
