# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0031_testmachine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmachine',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable name of this machine.', max_length=50, null=True),
        ),
    ]
