# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opensubmit', '0034_submissiontestresult_result_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_outcome_service_url', models.URLField()),
                ('lis_result_sourcedid', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltiresults', to='opensubmit.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltiresults', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='lti_key',
            field=models.CharField(blank=True, default='c74f4402cd4011e8a8d71c36bb30b620', help_text='Key to be used by an LTI consumer when accessing this course.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lti_secret',
            field=models.CharField(blank=True, default='c750487acd4011e882f91c36bb30b620', help_text='Secret to be used by an LTI consumer when accessing this course.', max_length=100, null=True),
        ),
    ]
