# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0035_auto_20181011_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lti_key',
            field=models.CharField(blank=True, default='7f349238e27d11e8b5f01c36bb30b620', help_text='Key to be used by an LTI consumer when accessing this course.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lti_secret',
            field=models.CharField(blank=True, default='7f35911ae27d11e8989f1c36bb30b620', help_text='Secret to be used by an LTI consumer when accessing this course.', max_length=100, null=True),
        ),
    ]
