__version__ = '0.35'

from django.apps import AppConfig
from django.db.models.signals import post_migrate

def ensure_user_groups(sender, **kwargs):
    """
        Make sure that all neccessary user groups exist and have the right permissions.
        The permission objects were already generated by the Django database initialization.

        The post_migrate signal has a nasty race condition, were some permission objects are not
        installed when the signal is triggered. We therefore warn the user accordingly.
    """
    from django.contrib.auth.models import Group, Permission

    tutor_perms = "add_submission", "change_submission", "delete_submission", "add_submissionfile", "change_submissionfile", "delete_submissionfile"
    owner_perms = "add_assignment", "add_grading", "add_gradingscheme", "add_submission", "add_submissionfile", "change_assignment", "change_course", "change_grading", "change_gradingscheme", "change_submission", "change_submissionfile", "delete_assignment", "delete_grading", "delete_gradingscheme", "delete_submission", "delete_submissionfile",

    tutor_group, created = Group.objects.get_or_create(name="Student Tutors")
    if created:
        try:
            tutor_group.permissions = [Permission.objects.get(codename=perm) for perm in tutor_perms]      
        except:
            print "WARNING: Permission generation incomplete, please re-run ./manage.py syncdb"
            return
        tutor_group.save()  

    owner_group, created = Group.objects.get_or_create(name="Course Owners")
    if created:
        try:
            owner_group.permissions = [Permission.objects.get(codename=perm) for perm in owner_perms]
        except:
            print "Permission generation incomplete, please re-run ./manage.py syncdb"
            return            
        owner_group.save()
    print "Permission generation complete."


class OpenSubmitAppConfig(AppConfig):
    name = "opensubmit"
    def ready(self):
        post_migrate.connect(ensure_user_groups, sender=self)

default_app_config = 'opensubmit.OpenSubmitAppConfig'